# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fastlane Action
      # You may pin to the exact commit or the version.
      # uses: maierj/fastlane-action@2121d31315dd0054a407c2c24938ae1fa29b883d
      uses: maierj/fastlane-action@v2.0.1
      with: 
        # The lane that should be executed.
        lane: appcenter_upload
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
